<?php
$options_new = array (
	array("name"=>"Vị trí sidebar",
		  "desc"=>"Lựa chọn",
		  "id"	=>$shortname."_pos_sidebar",
		  "type"=>"select",
		  "options" => array("Hiện sidebar trái","Hiện sidebar phải"),
		  "value" => "Hiện sidebar trái"),

    array("name"=>"Lọc sản phẩm",
        "desc"=>"Lựa chọn",
        "id"	=>$shortname."_filter_display",
        "type"=>"select",
        "options" => array("Hiện lọc sản phẩm","Ẩn lọc sản phẩm"),
        "value" => "Hiện lọc sản phẩm"),

	array("name"=>"Danh mục sản phẩm",
		  "desc"=>"Lựa chọn",
		  "id"	=>$shortname."_danh_muc_display",
		  "type"=>"select",
		  "options" => array("Hiện danh mục","Ẩn danh mục"),
		  "value" => "Hiện danh mục"),

    array("name"=>"Sản phẩm mới",
        "desc"=>"Lựa chọn",
        "id"	=>$shortname."_san_pham_moi_display",
        "type"=>"select",
        "options" => array("Hiện danh mục","Ẩn danh mục"),
        "value" => "Hiện danh mục"),

    array("name"=>"Sản phẩm nổi bật",
        "desc"=>"Lựa chọn",
        "id"	=>$shortname."_san_pham_noi_bat_display",
        "type"=>"select",
        "options" => array("Hiện danh mục","Ẩn danh mục"),
        "value" => "Hiện danh mục"),

    array("name"=>"Sản phẩm vừa xem",
        "desc"=>"Lựa chọn",
        "id"	=>$shortname."_san_pham_vua_xem_display",
        "type"=>"select",
        "options" => array("Hiện danh mục","Ẩn danh mục"),
        "value" => "Hiện danh mục"),

//	array(	"name" => "Thiết lập box giỏ hàng",
//			"type" => "titlesmall"),
//	array("name"=>"Giỏ hàng",
//		  "desc"=>"Lựa chọn",
//		  "id"	=>$shortname."_gio_hang_display",
//		  "type"=>"select",
//		  "options" => array("Hiện giỏ hàng","Ẩn giỏ hàng"),
//		  "value" => "Hiện giỏ hàng"),
//	array(	"name" => "Tiêu đề hộp giỏ hàng",
//			"desc" => "Nhập tiêu đề.",
//            "id" => $shortname."_gio_hang_title",
//			"value" => "Giỏ hàng",
//            "type" => "text"),
//	array(	"name" => "Thiết lập box tin mới nhất",
//			"type" => "titlesmall"),
//	array("name"=>"Tin mới nhất",
//		  "desc"=>"Lựa chọn",
//		  "id"	=>$shortname."_news_display",
//		  "type"=>"select",
//		  "options" => array("Hiện tin mới nhất","Ẩn tin mới nhất"),
//		  "value" => "Hiện tin mới nhất"),
//	array("name"=>"Số tin hiển thị",
//		  "desc"=>"Lựa chọn",
//		  "id"	=>$shortname."_news_number",
//		  "type"=>"select",
//		  "options" => array("4","8","12","16","20"),
//		  "value" => "8"),
//	array(	"name" => "Tiêu đề ô tin mới nhất",
//			"desc" => "Nhập tiêu đề.",
//            "id" => $shortname."_news_title",
//			"value" => "Tin tức mới nhất",
//            "type" => "text"),

);
$options=array_merge($options,$options_new);
if(array_key_exists('Chỉnh sửa Sidebar',$optionsGroup)){ $optionsGroup['Chỉnh sửa Sidebar']=array_merge($optionsGroup['Chỉnh sửa Sidebar'],$options_new); }else{ $optionsGroup=array_merge($optionsGroup,array('Chỉnh sửa Sidebar'=>$options_new));}
?>