<?php
$options_new = array (
	array(	"name" => "ID Danh mục trang chủ",
			"desc" => "Id các danh mục sẽ hiện các sản phẩm ở trang home",
			"id" => $shortname."_category_home",
			"value" => "",
			"type" => "text"),

    array(	"name" => "Chính sách",
        "type" => "titlesmall"),

    array(	"name" => "Đoạn văn bản trên title-item-1",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_1_text_1",
        "value" => "MIỄN PHÍ GIAO HÀNG",
        "type" => "text"),
    array(	"name" => "Đoạn văn bản trên header-item-1",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_header_1_text_1",
        "value" => "Nhận hàng trong vòng 30 ngày",
        "type" => "text"),

    array(	"name" => "Đoạn văn bản trên title-item-2",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_2_text_2",
        "value" => "QUÀ TẶNG",
        "type" => "text"),
    array(	"name" => "Đoạn văn bản trên header-item-2",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_header_2_text_2",
        "value" => "Nhiều quà tặng và ưu đãi hấp dẫn",
        "type" => "text"),

    array(	"name" => "Đoạn văn bản trên title-item-3",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_3_text_3",
        "value" => "BẢO ĐẢM CHẤT LƯỢNG",
        "type" => "text"),
    array(	"name" => "Đoạn văn bản trên header-item-3",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_header_3_text_3",
        "value" => "Sản phẩm kiểm định",
        "type" => "text"),

    array(	"name" => "Đoạn văn bản trên title-item-4",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_4_text_4",
        "value" => "HOTLINE: 08 7300 5757",
        "type" => "text"),
    array(	"name" => "Đoạn văn bản trên header-item-4",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_header_4_text_4",
        "value" => "Dịch vụ hỗ trợ 24/7",
        "type" => "text"),

    array(	"name" => "Tiêu đề banner",
        "type" => "titlesmall"),
    array(	"name" => "Tiêu đề banner trái",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_banner_left",
        "value" => "HOT",
        "type" => "text"),
      array(    "name" => "Link banner trái",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_link_banner_left",
        "value" => "#",
        "type" => "text"),
       array(   "name" => "Chọn hình nền banner trái",
        "desc" => "Thiêt lập hình nền",
        "id" => $shortname."_back_banner_left",
        "value" => "/themes/thanhlinh/css/images/index_banner_1.jpg",
        "type" => "image"),

    array(	"name" => "Tiêu đề banner giữa",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_banner_mid",
        "value" => "SEXY",
        "type" => "text"),
    array(  "name" => "Link banner giữa",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_link_banner_mid",
        "value" => "#",
        "type" => "text"),
    array(   "name" => "Chọn hình nền banner giữa",
        "desc" => "Thiêt lập hình nền",
        "id" => $shortname."_back_banner_mid",
        "value" => "/themes/thanhlinh/css/images/index_banner_2.jpg",
        "type" => "image"),

    array(	"name" => "Tiêu đề banner phải",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_banner_right",
        "value" => "TEEN",
        "type" => "text"),
        array(  "name" => "Link banner phải",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_link_banner_right",
        "value" => "#",
        "type" => "text"),
        array(   "name" => "Chọn hình nền banner phải",
        "desc" => "Thiêt lập hình nền",
        "id" => $shortname."_back_banner_right",
        "value" => "/themes/thanhlinh/css/images/index_banner_3.jpg",
        "type" => "image"),


    array(	"name" => "Title thương hiệu",
        "desc" => "Nhập sologan hoặc đoạn văn bản ngắn.",
        "id" => $shortname."_title_trademark",
        "value" => "Thương hiệu nổi tiếng",
        "type" => "text"),
    array(	"name" => "Thiết lập logo thương hiệu",
        "type" => "titlesmall"),
    array(	"name" => "Chọn logo thương hiệu 1",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_1",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_1.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 2",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_2",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_2.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 3",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_3",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_3.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 4",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_4",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_4.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 5",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_5",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_5.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 6",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_6",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_6.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 7",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_7",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_7.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 8",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_8",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_8.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 9",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_9",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_9.png",
        "type" => "image"),
    array(	"name" => "Chọn logo thương hiệu 10",
        "desc" => "Thiêt lập logo",
        "id" => $shortname."trademark_10",
        "value" => "/themes/thanhlinh/css/images/popular_brand_img_10.png",
        "type" => "image"),



);
$options=array_merge($options,$options_new);
if(array_key_exists('Trang chủ',$optionsGroup)){ $optionsGroup['Trang chủ']=array_merge($optionsGroup['Trang chủ'],$options_new); }else{ $optionsGroup=array_merge($optionsGroup,array('Trang chủ'=>$options_new));}
?>